version: "3"
services:
  front:
    build: "."
    container_name: front
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env.local
    ports:
      - 3000:3000
    command: /bin/sh -c  "yarn install && yarn dev"
